### ISSUE TITLE
Support magic dashboard for Passenger

### ISSUE THREAD

**Issue by shairyar** [appsignal/appsignal-ruby#730] opened 2021-05-28 07:48 UTC
I had a discussion about this with @matsimitsu, it seems that it can be done, but because it’s an external command we can’t just plonk it in a minutely probe and be done with it. It needs a lot of error handling around it to ensure it fails gracefully and It’s something that will take a little time to implement.

**Comment by shairyar** [comment] 2021-05-28 07:55
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700039333

**Comment by tombruijn** [comment] 2021-05-31 11:20
Duplicate of https://github.com/appsignal/appsignal-server/issues/3926

**Closed by tombruijn** 2021-05-31 11:20 UTC
Labels: enhancement
