### ISSUE TITLE
Handle kubernetes one-off jobs

### ISSUE THREAD

**Issue by matsimitsu** [appsignal/appsignal-ruby#282] opened 2017-04-26 12:38 UTC
When running a job in kubernetes, calling `Appsignal.stop` only ensures that the data is sent to the agent, but it doesn't guarantee that the agent has sent the data to our push API. 

Ideally calling `Appsignal.stop` will block until the Agent has shut down. This ensures that all data is sent before the container is killed.

**Comment by tombruijn** [comment] 2020-03-03 08:33
Duplicate of https://github.com/appsignal/appsignal-agent/issues/464
Closing

**Closed by tombruijn** 2020-03-03 08:33 UTC
Labels: feature
