### ISSUE TITLE
Appsignal::CheckIn.scheduler isn't thread-safe but looks like it is intended to be

### ISSUE THREAD

**Issue by Burgestrand** [appsignal/appsignal-ruby#1343] opened 2024-12-04 12:11 UTC
Hi! It might not actually *be a problem* to have multiple schedulers running. I'm just looking through the code to debug why I'm missing check-in events when using `.cron(...) { block }`, and spotted this.

TLDR: it's possible for there to be multiple `Appsignal::CheckIn::Scheduler` instances running, and it keeps itself alive.

https://github.com/appsignal/appsignal-ruby/blob/5697de35a055c385012ebade7b6b7208432add2d/lib/appsignal/check_in.rb#L93-L95

It's possible to spawn multiple schedulers if e.g. you call `Appsignal::CheckIn.cron(...)` from separate threads, if there's a context-switch during the execution of the `||=` operator.

Here's an example script to highlight the behaviour:
<details>
<summary>example script</summary>

```ruby
require "appsignal"

Event = Data.define(:thread, :event, :scheduler)

module Example
  # Simulate a delay in the initialization of the scheduler.
  module DelayInitialization
    def initialize(...)
      sleep(0.5)
      super
    end
  end
  Appsignal::CheckIn::Scheduler.prepend(DelayInitialization)

  @events = Thread::Queue.new
  class << self
    attr_reader :events

    def mark!(event)
      events << Event.new(Thread.current.name, event, Appsignal::CheckIn.scheduler)
    end

    def count_schedulers(id)
      schedulers = ObjectSpace.each_object(Appsignal::CheckIn::Scheduler)
      $stdout.puts "#{id}: #{schedulers.count}"
    end
  end
end

Example.count_schedulers("Before.")

Appsignal.start
threads = 2.times.map { |index|
  Thread.new do
    Thread.current.name = "Thread #{index}"
    Example.mark!("start")
    Appsignal::CheckIn.cron("thr1") do
      Example.mark!("checking in")
      sleep 1
    end
    Example.mark!("done")
  end
}

threads.each(&:join)
Example.events.close
Example.count_schedulers("After.")

$stdout.puts "Events:"
Example.events.size.times do
  event = Example.events.pop
  $stdout.puts "#{event.thread}: #{event.event} (#{event.scheduler&.__id__})"
end
```
</details>

Example output:
```
Before.: 0
After.: 2
Events:
Thread 0: start (680)
Thread 0: checking in (680)
Thread 1: start (700)
Thread 1: checking in (700)
Thread 0: done (700)
Thread 1: done (700)
```

## Workaround

Calling `Appsignal::CheckIn.scheduler` during application boot should be sufficient.
```[tasklist]
### Tasks
```

**Comment by tombruijn** [comment] 2024-12-05 09:34
Hi @Burgestrand, thanks for the report! We'll take a look.

**Comment by tombruijn** [comment] 2024-12-09 09:36
@unflxw might be interesting for you to look at?

**Comment by unflxw** [comment] 2024-12-09 09:55
Hi @Burgestrand, thank you again for reporting this! As you said, it is not necessarily _a problem_ to have several schedulers (on a long-running application, whichever one is not stored at `Appsignal::CheckIn.scheduler` should eventually just idle and do nothing) but it is certainly not intended behaviour. 

> I'm just looking through the code to debug why I'm missing check-in events when using .cron(...) { block }, and spotted this.

This might actually be the reason! When calling `Appsignal.stop`, it will call `Appsignal::CheckIn.scheduler.stop`, in order to wait for the scheduler to finish before shutting down AppSignal, and probably your application. If you have several schedulers, it will only stop the one assigned to `Appsignal::CheckIn.scheduler` -- meaning the check-ins that have been scheduled on the other scheduler may not be transmitted to AppSignal's servers before shutdown.

I'll see if it can be fixed in the manner you propose.

**Closed** 2024-12-13 09:43 UTC

**Comment by Burgestrand** [comment] 2024-12-17 08:15
Thanks!

**Comment by unflxw** [comment] 2024-12-19 15:49
Thanks to you @Burgestrand, for helping us make AppSignal better! I'm curious, has this fixed the issue with the missing cron check-ins that you were experiencing?
