### ISSUE TITLE
Support for rake tasks initiated by a cron job?

### ISSUE THREAD

**Issue by adamalbrecht** [appsignal/appsignal-ruby#237] opened 2017-01-20 20:18 UTC
I use the [Whenever](https://github.com/javan/whenever) gem to run cron jobs for my app. It just sets up my crontab file to execute rake tasks. So the tasks are executed like so:

`cd /path/to/my/app && RAILS_ENV=production bundle exec rake foo:bar --silent`

Is there a way to make AppSignal pick up errors generated by such a command?

Thanks!

**Comment by tombruijn** [comment] 2017-01-20 20:22
Hi @adamalbrecht!

Yes, AppSignal supports Rake tasks. If you have installed AppSignal in your project it should automatically start tracking errors.

More information can be found about it here: http://docs.appsignal.com/ruby/integrations/rake.html

Experiencing problems with the integration?

**Comment by adamalbrecht** [comment] 2017-01-20 20:28
@tombruijn Thanks for the quick response!

Yes I saw that page earlier, so I created a test rake task that raises an error and scheduled it to run every 15 minutes. I see in the log that it has run and failed multiple times, but I'm not seeing anything in AppSignal. 

I had just upgraded from 0.11.* to 2.0.5. Perhaps there is some configuration that I need to add?

**Comment by thijsc** [comment] 2017-01-20 20:41
It's possible that upgrade changed something, there were a lot of changes since the 0.11 series. Could you ping us on the chat in the app or send and e-mail to support@? There's probably some specific thing in your setup that trigger this.

**Comment by thijsc** [comment] 2017-01-20 20:45
These are the current docs for integrating with Rake by the way: http://docs.appsignal.com/ruby/integrations/rake.html

**Comment by adamalbrecht** [comment] 2017-01-20 21:27
It looks like there was an upgrade issue related to Capistrano. But I resolved that and the problem is still happening. So I don't think it's an upgrade issue. But I will ping you via chat.

**Comment by tombruijn** [comment] 2017-01-21 09:25
Looks like AppSignal wasn't loaded yet. We will update the docs to include this scenario.

Closing

**Closed by tombruijn** 2017-01-21 09:25 UTC

**Comment by sekretarot** [comment] 2022-12-13 08:01
Hello 🙋🏻‍♂️ 

After all these years, we are having a similar issue and we've had it for a while. Our cron jobs are not shown in AppSignal. 

Here is more info about our setup. 
- appsignal gem version is 2.11.6 
- We are using the `active_elastic_job` to run ActiveJob jobs on AWS ElasticBeanstalk worker instances with SQS standard queue. 

"Normal" worker jobs coming from the queue are shown in AppSignal correctly. 

The problem is that cron jobs are not available in AppSignal which makes monitoring those very hard for us. 

Can you please point us in the right direction so that we can also monitor the cron jobs in AppSignal?

Thanks

**Comment by tombruijn** [comment] 2022-12-14 09:25
Hi @sekretarot, we don't actively monitor closed issues (I saw this by chance), so I'd suggest creating a new issue in the future (and linking to this one) or contact us at support@appsignal.com.

For now, what type of monitoring are you missing from your cron jobs? We do not offer performance monitor for rake tasks out of the box, only errors.

This old gist of mine may help though to track performance metrics: https://gist.github.com/tombruijn/701a3c5e3f251fb5e3ba8f1f8e908887
For Rails apps I don't think lines 44 through 48 aren't needed, if the task depends on the `environment` task. If I recall correctly I needed some more feedback before adding this to the gem itself. So any feedback would be appreciated.
