### ISSUE TITLE
Appsignal agent turns into a zombie process

### ISSUE THREAD

**Issue by Wijnand** [appsignal/appsignal-ruby#675] opened 2020-12-30 07:13 UTC
Hi AppSignal,

since the 2.11.1 version of the Ruby Gem we are seeing zombie processes reported by our monitoring server.
After quick investigation this turns out to happen on both MacOS and Linux at least so I do not consider this an environment specific issue.

It also does not matter how the gem is loaded or what framework is being used, both when started from rails or just a simple ruby script running in the foreground results in a zombie process.

Reporting does seem to work just fine though, it is just a minor annoyance.

**Comment by ioki-cha** [comment] 2021-01-05 12:41
We've also spotted this on Linux on all our machines that run AppSignal:

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
758693   1195017  0.0  0.0      0     0 ?        Z    13:35   0:00 [appsignal-agent] <defunct>
758693   1195146  0.0  0.0      0     0 ?        Z    13:35   0:00 [appsignal-agent] <defunct>
758693   1196893  0.0  0.0      0     0 ?        Z    13:38   0:00 [appsignal-agent] <defunct>
```

Seems like some internal process might [not wait for its children correctly](https://linux.die.net/man/2/waitpid)?

**Comment by saboter** [comment] 2021-01-13 07:55
Same here. Spotted on Ubuntu 20.

**Comment by thijsc** [comment] 2021-01-19 07:30
Thanks for reporting! We're going to look into this.

**Comment by tombruijn** [comment] 2021-02-26 15:45
I can reproduce this as a change between 2.11.0 and 2.11.1.

I can reproduce on macOS and Linux (in docker) by starting the app, and then sending `kill -TERM <appsignal-agent PID>` (maybe a couple times). The agent process stops, but then a new `appsignal-agent` process gets started by our Ruby extension when it detects the `appsignal-agent` process is no longer running. Whenever it starts the agent, it first starts a new process before daemonizing that process. The process before it's daemonized is shown as "defunct" (in Linux). This defunct process isn't present in version 2.11.0.

```
$ ps aux | grep appsignal
root       152  0.0  0.0      0     0 pts/0    Z+   14:49   0:00 [appsignal-agent] <defunct>
root       174  0.0  0.0      0     0 pts/0    Z+   14:50   0:00 [appsignal-agent] <defunct>
root       230  0.0  0.0      0     0 pts/0    Z+   14:58   0:00 [appsignal-agent] <defunct>
root       231  0.0  0.4 282324 10152 ?        Ssl  14:58   0:00 /integration/ext/appsignal-agent
```
(I killed the agent processes a couple times)

For macOS, does the output of `ps aux` look similar to my output below for the `appsignal-agent` process? I think on macOS the parentheses indicate the defunct process.

```
ps aux | grep appsignal
tombruijn        48921   0.0  0.0        0      0 s000  Z+    4:10PM   0:00.00 (appsignal-agent)
tombruijn        48430   0.0  0.0        0      0 s000  Z+    3:55PM   0:00.00 (appsignal-agent)
tombruijn        48922   0.0  0.0  4306512   7216   ??  Ss    4:10PM   0:00.02 /Users/tombruijn/appsignal/ruby/ext/appsignal-agent
```
(I killed the agent processes a couple times)

If it's just the pre-daemonized processes perhaps we aren't "waiting" for it properly. We did update the agent from "c8f8185" to "361340a" ([diff (private link)](https://github.com/appsignal/appsignal-agent/compare/v-c8f8185...v-361340a)), but none of the changes immediately jump out at me as a potential cause for this behavior.

Whenever this behavior happens, either something is probably:

- killing the `appsignal-agent` process
- deleting the [working directory](https://docs.appsignal.com/ruby/configuration/options.html#option-working_directory_path), it shuts itself down when the directory is gone
- restarting the app through a master process manager

Does any of the above sound like something that could be happening in your setups? We're going to look into fixing it, but in case those defunct processes are bothering you can narrow down why it's happening.

**Comment by tombruijn** [comment] 2021-03-10 12:38
One small update, I have confirmed the defunct process is always there after boot without any of the 3 scenarios necessarily happening I mentioned earlier.

**Comment by tombruijn** [comment] 2021-03-15 10:38
Moving this issue to blocked because we now have two issues in progress and this issue is blocked on https://github.com/appsignal/appsignal-agent/issues/662

**Comment by tombruijn** [comment] 2021-08-12 11:37
We've published Ruby gem 3.0.12 with improvements for this. Please try it out and let us know if it still happens or not.

**Closed** 2021-08-12 11:37 UTC
Labels: bug

**Comment by Wijnand** [comment] 2021-08-24 10:47
We are still having Zombies with the latest Gem version. 
The zombie occurs quite soon after starting the Rails app via Passenger, the scenarios you describe do not seem to happen in our case.

The server is a simple AWS instance with Ubuntu 20.04, nothing special.

```
myuser@ip-10-0-2-241:~$ ps auxwww | grep appsignal
myuser+    2168  0.0  0.0      0     0 ?        Z    10:30   0:00 [appsignal-agent] <defunct>
myuser+    2266  0.0  0.5 344588 11440 ?        Ssl  10:30   0:00 /home/myuser/myuser/shared/bundle/ruby/2.7.0/gems/appsignal-3.0.13/ext/appsignal-agent
```

**Comment by tombruijn** [comment] 2021-09-06 09:26
Hi @Wijnand, I see one defunct appsignal-agent process and one running appsignal-agent process. This looks like the behavior I would expect on a standard Docker/container environment. Is this now only happening on you AWS server?

What happens is: the passenger process (your app) starts the appsignal-agent as a child process, but then it daemonizes the process, creating a new process. The old non-daemonized process exits. The parent process doesn't "reap" the now defunct process automatically on container systems. Containers behave differently than normal VPSes this way. The author of passenger [wrote something about this problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) as well.

From what I heard AWS has switched to containers under the hood mostly, so that may be what's causing it. Can you confirm that's how your setup appears to be? What AWS service are you using (EC2/ELB/etc)?

I'm more worried if you see multiple defunct processes, as long as you don't restart the app process in the container. Which would mean our gem for some reason restarts the agent over and over because it can't connect to it.
