### ISSUE TITLE
Appsignal breaking causes application crash

### ISSUE THREAD

**Issue by fagiani** [appsignal/appsignal-ruby#823] opened 2022-02-17 00:00 UTC
## Describe the bug

A clear and concise description of what the bug is including the code used and the exception backtrace, if any.

```
2022-02-16 20:50:50I, [2022-02-16T23:50:50.188413 #32] INFO -- : Started GET "/" for [10.0.0.91](http://10.0.0.91/) at 2022-02-16 23:50:50 +0000
2022-02-16 20:50:50F, [2022-02-16T23:50:49.987864 #29] FATAL -- :
2022-02-16 20:50:50F, [2022-02-16T23:50:50.177205 #29] FATAL -- : NoMethodError (undefined method `any?' for nil:NilClass):
2022-02-16 20:50:50F, [2022-02-16T23:50:50.177278 #29] FATAL -- :
2022-02-16 20:50:50F, [2022-02-16T23:50:50.177393 #29] FATAL -- : appsignal (3.0.21) lib/appsignal/hooks/active_support_notifications.rb:19:in `block in instrument'
2022-02-16 20:50:50appsignal (3.0.21) lib/appsignal/hooks/active_support_notifications.rb:18:in `instrument'
2022-02-16 20:50:50appsignal (3.0.21) lib/appsignal/rack/rails_instrumentation.rb:32:in `call_with_appsignal_monitoring'
2022-02-16 20:50:50appsignal (3.0.21) lib/appsignal/rack/rails_instrumentation.rb:17:in `call'
2022-02-16 20:50:50appsignal (3.0.21) lib/appsignal/integrations/unicorn.rb:16:in `worker_loop'
2022-02-16 20:50:50/app/bin/bundle:3:in `load'
2022-02-16 20:50:50/app/bin/bundle:3:in `<main>'
```

## To Reproduce

- Using AppSignal for Ruby gem version 2.9.8, 3.0.3, 3.0.21
- In my app using Rails version 5.2.4.5
- Just boot app with: `bundle exec unicorn -p 3000 -c ./config/unicorn.conf`

**Comment by tombruijn** [comment] 2022-02-17 09:50
Hi @fagiani, I've tried to reproduce it, but I can't seem to. I've tested on Rails version  5.2.5 (I can't install 5.2.4.5 exactly because of an mimemagick extension install error). There aren't any differences between the ActiveSupport::Notifications implementation between those two Rails versions.

I don't quite understand the error message or backtrace. We don't call `any?` on those lines. There seem to be lines missing of where this `NoMethodError` occurs.

Can you get more information about this error, like a full backtrace or send us an app in which this issue can be reproduced? If you use any other APM gems in this app, please let us know too.

**Comment by fagiani** [comment] 2022-02-18 14:04
Hello @tombruijn my guess is that it should have to do with a `unicorn` configuration... not sure if `preload_app true` or any before or after fork settings... I've momentarily disabled it as Honeybadger worked.

All there is was what I placed on the issue. I agree that the stack trace is quite odd but I pasted all of it.

I cannot send the app as it is from a customer.

**Comment by tombruijn** [comment] 2022-02-18 15:30
I'm also unable to reproduce it with `preload_app true`. Can you share more of your `unicorn.conf` file? You can send it to support@appsignal.com (please mention this issue).

Was another tool like honeybadger also installed together with AppSignal? We've seen that can sometimes interfere with one another.

**Comment by fagiani** [comment] 2022-02-22 12:58
Just sent @tombruijn! Keep Rocking!

**Comment by shairyar** [comment] 2022-02-22 13:58
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700094271 (private link) 

cc @tombruijn

**Comment by luismiramirez** [comment] 2022-02-24 09:20
Hi @fagiani, I've used your unicorn config and still can't reproduce the issue. Could you try disabling Honeybadger to see if that fixes the issue? As @tombruijn mentioned, that can cause conflicts.

**Comment by luismiramirez** [comment] 2022-05-02 14:20
Hi @fagiani is this still an issue for you?

**Comment by luismiramirez** [comment] 2022-05-11 09:50
I am closing this for now. Feel free to reply to this issue if the problem persists so we can reopen it and keep researching.

**Closed by luismiramirez** 2022-05-11 09:50 UTC
Labels: bug
