### ISSUE TITLE
DelayedJob Monitoring Infinite Loop in development environment

### ISSUE THREAD

**Issue by cec** [appsignal/appsignal-ruby#104] opened 2016-04-26 19:19 UTC
Hi,

I'm running the latest version of the gem.

My jobs end up in an infinte loop after although job's perform is completed.
Stepping with the debugger, I noticed that this loop happens in the monitoring code of Appsignal.
Here is an abbreviated version of the stack trace, just to explain the situation:

```
Appsignal::Transaction.sanitized_session_data
...
Appsignal::Transaction.complete
Appsignal::Transaction::complete_current
...
```

Basically, once the job is complete and Appsignal is called to complete the "monitoring transaction", it tries to retrieve session data, which is not available in a background job, in the second line of the method body (`return unless session = request.session`), which calls `ActionDispatch::TestProcess.session` that ends up in an infinte loop for some reason I didn't manage to figure out.

```
    def sanitized_session_data
      return if Appsignal.config[:skip_session_data] || !request.respond_to?(:session)
      return unless session = request.session
      Appsignal::ParamsSanitizer.sanitize(session.to_hash)
    end
```

What should I do?
Is it possible to temporarily disable background monitoring?

Thanks!

P.S.: tomorrow morning I'll try with a simple job just in case to verify that it's not something related to my code.

**Comment by thijsc** [comment] 2016-04-28 18:56
Are you running DJ with something like `script/rails delayed_job start`? If so this is probably caused by a compatibility issue with the Daemons gem that DJ uses under the hood we're currently in the process of debugging and fixing.

There's some more information here: https://github.com/thuehlinger/daemons/issues/47

**Comment by cec** [comment] 2016-04-29 13:58
Hi @thijsc,

in production I start DJ from capistrano using [this gem](https://github.com/AgileConsultingLLC/capistrano3-delayed-job) which calls
`bundle exec script/delayed_job  -n 1 --pool=.... --pool=.... restart`

in development I start DJ with the [rake task jobs:work](https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/tasks.rb) 

The problem occurred only once in production, but is consistent in development.

**Comment by cec** [comment] 2016-05-01 12:34
Hi @thijsc ,

I got more information about the problem, specifically, I found out why it happens in development and not in production.

I had an error in my Gemfile:

```
group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'sunspot-rails-tester
  gem 'capybara'
  gem 'launchy'
  gem 'capybara-screenshot'
  gem 'capybara-webkit'
end
```

Probably because of a copy-paste, I was requiring spec gems in development.
This resulted in Appsignal::Transaction::GenericRequest to have its ancestors chain become 

```
[
"Appsignal::Transaction::GenericRequest", 
"Object", 
"ActionDispatch::TestProcess", 
"Delayed::MessageSending", 
"ActiveSupport::Dependencies::Loadable", 
"FriendlyId::ObjectUtils", 
"JSON::Ext::Generator::GeneratorMethods::Object", 
"PP::ObjectMixin", 
"Kernel", 
"BasicObject"
]
```

instead of this:

```
[
"Appsignal::Transaction", 
"Object", 
"Delayed::MessageSending", 
"ActiveSupport::Dependencies::Loadable", 
"FriendlyId::ObjectUtils", 
"JSON::Ext::Generator::GeneratorMethods::Object", 
"PP::ObjectMixin", 
"Kernel", 
"BasicObject"
]
```

This led Appsignal's code to expect GenericRequest to have a session, which resulted in an infinite loop (for some reason I cannot fathom).

While running specs, Appsignal is not meant to be active. 
I'm monitoring my dev environment for a bunch of reasons, but most people won't face this issue at all.

From my point of view this issue is closed.
In case people make my same mistake, this could save quite a headache cause for me it was hard to track down.

Cheers and kudos for your awesome work!

**Comment by thijsc** [comment] 2016-05-03 12:09
I will take a look at that infinite loop. That shouldn't be possible, even in weird circumstances. Leaving this issue open for that.

Thanks for this great debugging session!

**Comment by cec** [comment] 2016-05-03 12:51
I see, glad it helps you guys too :)

**Comment by thijsc** [comment] 2016-05-31 13:57
I've had trouble reproducing this. I think it might be relevant only in this specific scenario when using Spring. Closing this issue.

**Closed by thijsc** 2016-05-31 13:57 UTC

**Comment by conarro** [comment] 2020-06-10 10:58
Just ran into the same underlying issue (`Stack level too deep` related to `request.session`), but not related to DJ.

**Reproduction steps**
* In `appsignal.yml`: set Appsignal `active: true` in the test environment, and ensure `skip_session_data` is `true` (this is the default, so if it isn't defined in your config that should work)
* Add `include ActionDispatch::TestProcess` globally in specs (e.g. via `rails_helper`) -- we had this in place to make `fixture_file_upload` available to use in factories
* If you don't have one, write a test to ensure Appsignal works. For us, we had a class reporting a handled error (via `Appsignal.send_error`), and we had a spec for that code to ensure the errors got sent to Appsignal. E.g. for RSpec: `expect(Appsignal).to receive(:send_error).with(StandardError)`
* Run the spec, see `Stack level too deep` errors (with `lib/action_dispatch/testing/test_process.rb` in the stack trace)

**How we fixed it**
* Some Googling (query: `actionpack request session test stacklevel`) brought me to [this SO post](https://stackoverflow.com/questions/13673639/accessing-session-from-a-helper-spec-in-rspec), which indicates a similar problem, the underlying cause being the use of `include ActionDispatch::TestProcess`
* A link from that SO post goes here https://github.com/activeadmin/activeadmin/issues/512, which has [this comment indicating a similar thing](https://github.com/activeadmin/activeadmin/issues/512#issuecomment-11129022)
* With this info, removed our `include ActionDispatch::TestProcess` in `rails_helper.rb` and replaced our use of `fixture_file_upload` in factories to use `Rack::Test::UploadedFile.new`

---

This doesn't feel like an Appsignal-specific issue, but I wanted to post here for future reference.
